In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"minzzzzi","key":"74a980fb52033cf0ead89c84120a4a9c"}'}

In [ ]:
!pip uninstall -y kaggle
!pip install --upgrade pip
!pip install kaggle

Uninstalling kaggle-1.5.6:
  Successfully uninstalled kaggle-1.5.6
     |████████████████████████████████| 1.5MB 6.9MB/s 
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
     |████████████████████████████████| 58 kB 2.9 MB/s 
  Created wheel for kaggle: filename=kaggle-1.5.6-py3-none-any.whl size=72859 sha256=8ecefdd324886b330443e8b783f38ff77acb5f3fa5e1d271567f4079711ca6ae
  Stored in directory: /root/.cache/pip/wheels/01/3e/ff/77407ebac3ef71a79b9166a8382aecf88415a0bcbe3c095a01
Successfully built kaggle


In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle competitions download digit-recognizer

 59% 9.00M/15.3M [00:00<00:00, 24.8MB/s]
100% 15.3M/15.3M [00:00<00:00, 36.7MB/s]


In [ ]:
!unzip digit-recognizer.zip

Archive:  digit-recognizer.zip
  inflating: sample_submission.csv   
  inflating: test.csv                
  inflating: train.csv               


In [ ]:
import torch
import torch.optim as optim
import torch.nn.functional as F
import pandas as pd
import numpy as np
import random
from sklearn.preprocessing import MinMaxScaler

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

random.seed(777)
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [ ]:
train = pd.read_csv('train.csv',header = None)
test = pd.read_csv('test.csv',header = None)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,2

In [ ]:
train 

0       1       2       3    ...       781       782       783       784
0      label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
1          1       0       0       0  ...         0         0         0         0
2          0       0       0       0  ...         0         0         0         0
3          1       0       0       0  ...         0         0         0         0
4          4       0       0       0  ...         0         0         0         0
...      ...     ...     ...     ...  ...       ...       ...       ...       ...
41996      0       0       0       0  ...         0         0         0         0
41997      1       0       0       0  ...         0         0         0         0
41998      7       0       0       0  ...         0         0         0         0
41999      6       0       0       0  ...         0         0         0         0
42000      9       0       0       0  ...         0         0         0         0

[42001 rows x 785 columns]

In [ ]:
lr = 0.001
epochs = 15
batch_size = 100

In [ ]:
x_train = train.loc[1:,1:]
y_train = train.loc[1:,0]

x_train = np.array(x_train,dtype=float)
y_train = np.array(y_train,dtype=float)

x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

y_train[:5]

tensor([1, 0, 1, 4, 0])

In [ ]:
train_dataset = torch.utils.data.TensorDataset(x_train,y_train)

In [ ]:
data_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                          batch_size = batch_size,
                                          shuffle = True,
                                          drop_last = True)

In [ ]:
linear1 = torch.nn.Linear(784,512,bias = True)
linear2 = torch.nn.Linear(512,512,bias = True)
linear3 = torch.nn.Linear(512,512,bias = True)
linear4 = torch.nn.Linear(512,512,bias = True)
linear5 = torch.nn.Linear(512,10,bias = True)

relu = torch.nn.ReLU()
dropout = torch.nn.Dropout(p = 0.3)

torch.nn.init.xavier_uniform_(linear1.weight)
torch.nn.init.xavier_uniform_(linear2.weight)
torch.nn.init.xavier_uniform_(linear3.weight)
torch.nn.init.xavier_uniform_(linear4.weight)
torch.nn.init.xavier_uniform_(linear5.weight)

Parameter containing:
tensor([[-0.0427, -0.0736,  0.1044,  ...,  0.0265,  0.0757,  0.0033],
        [-0.0812, -0.0061,  0.0893,  ..., -0.0484, -0.1041,  0.0467],
        [ 0.0336,  0.0358, -0.1038,  ..., -0.0965,  0.0175,  0.0510],
        ...,
        [ 0.0894,  0.0552, -0.0498,  ..., -0.0920, -0.0768,  0.0880],
        [-0.0811, -0.0442,  0.0215,  ..., -0.0213, -0.0758, -0.0643],
        [ 0.0282,  0.0388, -0.0232,  ..., -0.0314,  0.0278, -0.0487]],
       requires_grad=True)

In [ ]:
model = torch.nn.Sequential(linear1,relu,dropout,
                            linear2,relu,dropout,
                            linear3,relu,dropout,
                            linear4,relu,dropout,
                            linear5).to(device)

In [ ]:
loss = torch.nn.CrossEntropyLoss().to(device)
optimzier = optim.Adam(model.parameters(),lr = lr)

In [ ]:
total_batch = len(data_loader)
for epoch in range(epochs):
  avg_cost = 0
  for x,y in data_loader:
    x = x.to(device)
    y = y.to(device)


    optimzier.zero_grad()

    hypo = model(x)

    cost = loss(hypo,y)

    cost.backward()

    optimzier.step()

    avg_cost += cost / total_batch

  print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))


Epoch: 0001 cost = 0.159369588
Epoch: 0002 cost = 0.147060469
Epoch: 0003 cost = 0.158277452
Epoch: 0004 cost = 0.158608392
Epoch: 0005 cost = 0.151973248
Epoch: 0006 cost = 0.152952239
Epoch: 0007 cost = 0.143649340
Epoch: 0008 cost = 0.143961623
Epoch: 0009 cost = 0.137443841
Epoch: 0010 cost = 0.139646903
Epoch: 0011 cost = 0.139382333
Epoch: 0012 cost = 0.130148724
Epoch: 0013 cost = 0.127227738
Epoch: 0014 cost = 0.126948446
Epoch: 0015 cost = 0.129969433


In [ ]:
test = pd.read_csv('test.csv',header = None)
test[:5]

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,2

0       1       2       3    ...       780       781       782       783
0  pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
1       0       0       0       0  ...         0         0         0         0
2       0       0       0       0  ...         0         0         0         0
3       0       0       0       0  ...         0         0         0         0
4       0       0       0       0  ...         0         0         0         0

[5 rows x 784 columns]

In [ ]:
test = test.loc[1:,:]
test = np.array(test,dtype= float)
test = torch.FloatTensor(test).to(device)

In [ ]:
with torch.no_grad():
  prediction = model(test)
  predict =  torch.argmax(prediction,1)

In [ ]:
predict[:5]

tensor([2, 0, 9, 9, 3], device='cuda:0')

In [ ]:
submit = pd.read_csv('sample_submission.csv')
submit

ImageId  Label
0            1      0
1            2      0
2            3      0
3            4      0
4            5      0
...        ...    ...
27995    27996      0
27996    27997      0
27997    27998      0
27998    27999      0
27999    28000      0

[28000 rows x 2 columns]

In [ ]:
predict = predict.cpu().numpy().reshape(-1,1)
predict

array([[2],
       [0],
       [9],
       ...,
       [3],
       [9],
       [2]])

In [ ]:
submit['Label'] = predict

In [ ]:
submit[:5]

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [ ]:
submit.to_csv('submission.csv',index=False,header=True)

!kaggle competitions submit -c digit-recognizer -f submission.csv -m "Message"

100% 208k/208k [00:03<00:00, 68.0kB/s]
Successfully submitted to Digit Recognizer